"""update sub and package tables

Revision ID: 401dc74856ff
Revises: 0b62d82e3eb9
Create Date: 2025-02-24 03:15:26.273250

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '401dc74856ff'
down_revision = '0b62d82e3eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('max_workplaces', sa.Integer(), nullable=False))
    op.drop_column('package', 'max_workspaces')
    op.add_column('subscription', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'status')
    op.add_column('package', sa.Column('max_workspaces', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('package', 'max_workplaces')
    # ### end Alembic commands ###
