"""update subs table

Revision ID: 9428c282dea5
Revises: 401dc74856ff
Create Date: 2025-02-25 05:32:06.470627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9428c282dea5'
down_revision = '401dc74856ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('active_date', sa.DateTime(), nullable=False))
    op.add_column('subscription', sa.Column('expired_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'expired_date')
    op.drop_column('subscription', 'active_date')
    # ### end Alembic commands ###
