"""no max employees

Revision ID: 9d3544f982ec
Revises: d6f3b555e7b8
Create Date: 2025-03-04 12:58:00.736945

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d3544f982ec'
down_revision = 'd6f3b555e7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('org_slug_key', 'org', type_='unique')
    op.drop_column('org', 'max_empoyees')
    op.drop_column('org', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('max_empoyees', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('org_slug_key', 'org', ['slug'])
    # ### end Alembic commands ###
